# Customize #########################################################
homeassistant:
  customize:
  # Switches ###########
    switch.mower_mowing:
      friendly_name: Taglio
    switch.mower_home:
      friendly_name: Alla Base
    switch.mower_edgecut:
      friendly_name: Taglio Perimetrale
    switch.mower_partymode:
      friendly_name: Modalità Party
    switch.mower_lock:
      friendly_name: Blocco

  # Sensors ############
    sensor.landroid_mower_battery:
      friendly_name: In Ricarica
      device_class: battery
    sensor.landroid_mower_error:
      friendly_name: Errore
    sensor.landroid_mower_status:
      friendly_name: Stato

    sensor.mower_ip:
      friendly_name: Indirizzo IP

    sensor.mower_bladetime:
      friendly_name: Tempo di Taglio
    sensor.mower_current_bladetime:
      friendly_name: Tempo di taglio corrente
    sensor.mower_totaltime:
      friendly_name: Tempo totale
    sensor.mower_distance:
      friendly_name: Distanza
    sensor.mower_lastupdate:
      friendly_name: Ultimo aggiornamento
      icon: mdi:update
    sensor.mower_wifi:
      friendly_name: Qualità WiFi
    sensor.mower_yaw:
      friendly_name: Imbardata
    sensor.mower_roll:
      friendly_name: Incliazione Laterale
    sensor.mower_pitch:
      friendly_name: Pendenza

  # Input Selects ######
    input_select.mower_zone:
      friendly_name: Zona di Taglio

  # Input Numbers ######
    input_number.mower_raindelay:
      friendly_name: Ritardo Piogga
    input_number.mower_timeextension:
      friendly_name: Estensione Tempo

    input_number.mower_zone0_distance:
      friendly_name: "Zona di Taglio 0: Distanza"
    input_number.mower_zone1_distance:
      friendly_name: "Zona di Taglio 1: Distanza"
    input_number.mower_zone2_distance:
      friendly_name: "Zona di Taglio 2: Distanza"
    input_number.mower_zone3_distance:
      friendly_name: "Zona di Taglio 3: Distanza"

    input_number.mower_zone0_probability:
      friendly_name: "Zona di Taglio 0: Probabilità"
    input_number.mower_zone1_probability:
      friendly_name: "Zona di Taglio 1: Probabilità"
    input_number.mower_zone2_probability:
      friendly_name: "Zona di Taglio 2: Probabilità"
    input_number.mower_zone3_probability:
      friendly_name: "Zona di Taglio 3: Probabilità"

  # Input Booleans #####
    input_boolean.mower_sched_settings:
      friendly_name: Impostazioni
    input_boolean.mower_info_toggle:
      friendly_name: Informazioni
    input_boolean.mower_zone_enable:
      friendly_name: Attiva multi-zona

    input_boolean.mower_view_config:
      friendly_name: Configurazione
    input_boolean.mower_view_setzones:
      friendly_name: Multi-zona

    #input_boolean.mower_view_0:
    #  friendly_name: Do.
    #input_boolean.mower_view_1:
    #  friendly_name: Lu.
    #input_boolean.mower_view_2:
    #  friendly_name: Ma.
    #input_boolean.mower_view_3:
    #  friendly_name: Me.
    #input_boolean.mower_view_4:
    #  friendly_name: Gi.
    #input_boolean.mower_view_5:
    #  friendly_name: Ve.
    #input_boolean.mower_view_6:
    #  friendly_name: Sa.

    #input_boolean.mower_0_sched_enable:
    #  friendly_name: Domenica
    #input_boolean.mower_1_sched_enable:
    #  friendly_name: Lunedì
    #input_boolean.mower_2_sched_enable:
    #  friendly_name: Martedì
    #input_boolean.mower_3_sched_enable:
    #  friendly_name: Mercoledì
    #input_boolean.mower_4_sched_enable:
    #  friendly_name: Giovedì
    #input_boolean.mower_5_sched_enable:
    #  friendly_name: Venerdì
    #input_boolean.mower_6_sched_enable:
    #  friendly_name: Sabato

    #input_boolean.mower_0_cuttoedge:
    #  friendly_name: Taglio Perimetrale
    #input_boolean.mower_1_cuttoedge:
    #  friendly_name: Taglio Perimetrale
    #input_boolean.mower_2_cuttoedge:
    #  friendly_name: Taglio Perimetrale
    #input_boolean.mower_3_cuttoedge:
    #  friendly_name: Taglio Perimetrale
    #input_boolean.mower_4_cuttoedge:
    #  friendly_name: Taglio Perimetrale
    #input_boolean.mower_5_cuttoedge:
    #  friendly_name: Taglio Perimetrale
    #input_boolean.mower_6_cuttoedge:
    #  friendly_name: Taglio Perimetrale


  # Automations ########
    automation.mower_notify_status:
      friendly_name: Status notification
      icon: mdi:bell
    automation.mower_notify_error:
      friendly_name: Error notification
      icon: mdi:bell

    automation.mower_sync_values:
      friendly_name: Data synchronization
      icon: mdi:sync

    #automation.mower_views_switch:
    #  friendly_name: Mostra/Nascondi tab
    #  icon: mdi:tab


# Scripts #########
    script.mower_set_config:
      friendly_name: Applica
      icon: mdi:content-save-settings

    script.mower_setzone:
      friendly_name: Selezione Zona
      icon: mdi:vector-difference

    script.mower_setzones:
      friendly_name: Applica multi-zona
      icon: mdi:content-save-settings

    script.mower_views_toggle:
      friendly_name: Mostra/Nascondi tab
      icon: mdi:tab
