# Customize #########################################################
homeassistant:
  customize:
  # Switches ###########
    switch.mower_mowing:
      friendly_name: Tonte
    switch.mower_home:
      friendly_name: Retour à la maison
    switch.mower_edgecut:
      friendly_name: Coupe à bord
    switch.mower_partymode:
      friendly_name: Mode de fete
    switch.mower_lock:
      friendly_name: La serrure

  # Sensors ############
    sensor.landroid_mower_battery:
      friendly_name: Charge de la batterie
      device_class: battery
    sensor.landroid_mower_error:
      friendly_name: Erreur
    sensor.landroid_mower_status:
      friendly_name: Status

    sensor.mower_ip:
      friendly_name: Adresse IP

    sensor.mower_bladetime:
      friendly_name: Temps de coupe des lames
    sensor.mower_current_bladetime:
      friendly_name: Actuel temps de coupe des lames
    sensor.mower_totaltime:
      friendly_name: Temps de travail
    sensor.mower_distance:
      friendly_name: Distance parcourue
    sensor.mower_lastupdate:
      friendly_name: Dernière mise à jour
      icon: mdi:update
    sensor.mower_wifi:
      friendly_name: Qualité de la connexion Wifi
    sensor.mower_yaw:
      friendly_name: Azimut
    sensor.mower_roll:
      friendly_name: Roulis
    sensor.mower_pitch:
      friendly_name: Tangage

  # Input Selects ######
    input_select.mower_zone:
      friendly_name: Zone de tonte

  # Input Numbers ######
    input_number.mower_raindelay:
      friendly_name: Délai de pluie
    input_number.mower_timeextension:
      friendly_name: Délais supplémentaire

    input_number.mower_zone0_distance:
      friendly_name: "Zone de tonte 0: Distance"
    input_number.mower_zone1_distance:
      friendly_name: "Zone de tonte 1: Distance"
    input_number.mower_zone2_distance:
      friendly_name: "Zone de tonte 2: Distance"
    input_number.mower_zone3_distance:
      friendly_name: "Zone de tonte 3: Distance"

    input_number.mower_zone0_probability:
      friendly_name: "Zone de tonte 0: Probabilité"
    input_number.mower_zone1_probability:
      friendly_name: "Zone de tonte 1: Probabilité"
    input_number.mower_zone2_probability:
      friendly_name: "Zone de tonte 2: Probabilité"
    input_number.mower_zone3_probability:
      friendly_name: "Zone de tonte 3: Probabilité"

  # Input Booleans #####
    input_boolean.mower_sched_settings:
      friendly_name: Paramètres
    input_boolean.mower_info_toggle:
      friendly_name: Informations
    input_boolean.mower_zone_enable:
      friendly_name: Activer le multizone

    input_boolean.mower_view_config:
      friendly_name: Configuration
    input_boolean.mower_view_setzones:
      friendly_name: Multizone

    #input_boolean.mower_view_0:
    #  friendly_name: Di.
    #input_boolean.mower_view_1:
    #  friendly_name: Lu.
    #input_boolean.mower_view_2:
    #  friendly_name: Ma.
    #input_boolean.mower_view_3:
    #  friendly_name: Me.
    #input_boolean.mower_view_4:
    #  friendly_name: Je.
    #input_boolean.mower_view_5:
    #  friendly_name: Ve.
    #input_boolean.mower_view_6:
    #  friendly_name: Sa.

    #input_boolean.mower_0_sched_enable:
    #  friendly_name: Dimanche
    #input_boolean.mower_1_sched_enable:
    #  friendly_name: Lundi
    #input_boolean.mower_2_sched_enable:
    #  friendly_name: Mardi
    #input_boolean.mower_3_sched_enable:
    #  friendly_name: Mercredi
    #input_boolean.mower_4_sched_enable:
    #  friendly_name: Jeudi
    #input_boolean.mower_5_sched_enable:
    #  friendly_name: Vendredi
    #input_boolean.mower_6_sched_enable:
    #  friendly_name: Samedi

    #input_boolean.mower_0_cuttoedge:
    #  friendly_name: Coupe à bord
    #input_boolean.mower_1_cuttoedge:
    #  friendly_name: Coupe à bord
    #input_boolean.mower_2_cuttoedge:
    #  friendly_name: Coupe à bord
    #input_boolean.mower_3_cuttoedge:
    #  friendly_name: Coupe à bord
    #input_boolean.mower_4_cuttoedge:
    #  friendly_name: Coupe à bord
    #input_boolean.mower_5_cuttoedge:
    #  friendly_name: Coupe à bord
    #input_boolean.mower_6_cuttoedge:
    #  friendly_name: Coupe à bord


  # Automations ########
    automation.mower_notify_status:
      friendly_name: Notification de status Landroid
      icon: mdi:bell
    automation.mower_notify_error:
      friendly_name: Notification d'erreurs Landroid
      icon: mdi:bell

    automation.mower_sync_values:
      friendly_name: Mise à jour des données Landroid
      icon: mdi:sync

    #automation.mower_views_switch:
    #  friendly_name: Carte d'enregistrement umschalten
    #  icon: mdi:tab


# Scripts #########
    script.mower_set_config:
      friendly_name: Enregistrer la configuration
      icon: mdi:content-save-settings

    script.mower_setzone:
      friendly_name: Sélection des zones
      icon: mdi:vector-difference

    script.mower_setzones:
      friendly_name: Enregistrer la multizone
      icon: mdi:content-save-settings

    script.mower_views_toggle:
      friendly_name: Basculer les onglets
      icon: mdi:tab
