# Customize #########################################################
homeassistant:
  customize:
    # Switches ###########
    switch.mower_mowing:
      friendly_name: Koszenie
    switch.mower_home:
      friendly_name: Home
    switch.mower_edgecut:
      friendly_name: Cut-to-edge
    switch.mower_partymode:
      friendly_name: Partymode
    switch.mower_lock:
      friendly_name: Blockada

    # Sensors ############
    sensor.landroid_mower_battery:
      friendly_name: Ładowanie akumulatora
      device_class: battery
    sensor.landroid_mower_error:
      friendly_name: Błąd
    sensor.landroid_mower_status:
      friendly_name: Status

    sensor.mower_ip:
      friendly_name: IP address

    sensor.mower_bladetime:
      friendly_name: Czas pracy ostrzy
    sensor.mower_current_bladetime:
      friendly_name: Obecny czas ostrzy
    sensor.mower_totaltime:
      friendly_name: Czas całkowity
    sensor.mower_distance:
      friendly_name: Odległość
    sensor.mower_lastupdate:
      friendly_name: Ostatnia aktualizacja
      icon: mdi:update
    sensor.mower_wifi:
      friendly_name: Jakość WiFi
    sensor.mower_yaw:
      friendly_name: Yaw
    sensor.mower_roll:
      friendly_name: Roll
    sensor.mower_pitch:
      friendly_name: Pitch

    # Input Selects ######
    input_select.mower_zone:
      friendly_name: Strefa koszenia

    # Input Numbers ######
    input_number.mower_raindelay:
      friendly_name: Czujnik deszczu
    input_number.mower_timeextension:
      friendly_name: Wydłużenie czasu

    input_number.mower_zone0_distance:
      friendly_name: "Strefa koszenia 0: odległość"
    input_number.mower_zone1_distance:
      friendly_name: "Strefa koszenia 1: odległość"
    input_number.mower_zone2_distance:
      friendly_name: "Strefa koszenia 2: odległość"
    input_number.mower_zone3_distance:
      friendly_name: "Strefa koszenia 3: odległość"

    input_number.mower_zone0_probability:
      friendly_name: "Strefa koszenia 0: Prawdopodobieństwo"
    input_number.mower_zone1_probability:
      friendly_name: "Strefa koszenia 1: Prawdopodobieństwo"
    input_number.mower_zone2_probability:
      friendly_name: "Strefa koszenia 2: Prawdopodobieństwo"
    input_number.mower_zone3_probability:
      friendly_name: "Strefa koszenia 3: Prawdopodobieństwo"

    # Input Booleans #####
    input_boolean.mower_sched_settings:
      friendly_name: Ustawienia
    input_boolean.mower_info_toggle:
      friendly_name: Informacje
    input_boolean.mower_zone_enable:
      friendly_name: Włącz wielostrefowość

    input_boolean.mower_view_config:
      friendly_name: Konfiguracja
    input_boolean.mower_view_setzones:
      friendly_name: Wielostrefowość

    #input_boolean.mower_view_0:
    #  friendly_name: Nd.
    #input_boolean.mower_view_1:
    #  friendly_name: Pn.
    #input_boolean.mower_view_2:
    #  friendly_name: Wt.
    #input_boolean.mower_view_3:
    #  friendly_name: Śr.
    #input_boolean.mower_view_4:
    #  friendly_name: Cz.
    #input_boolean.mower_view_5:
    #  friendly_name: Pt.
    #input_boolean.mower_view_6:
    #  friendly_name: So.

    #input_boolean.mower_0_sched_enable:
    #  friendly_name: Niedziela
    #input_boolean.mower_1_sched_enable:
    #  friendly_name: Poniedziałek
    #input_boolean.mower_2_sched_enable:
    #  friendly_name: Wtorek
    #input_boolean.mower_3_sched_enable:
    #  friendly_name: Środa
    #input_boolean.mower_4_sched_enable:
    #  friendly_name: Czwartek
    #input_boolean.mower_5_sched_enable:
    #  friendly_name: Piątek
    #input_boolean.mower_6_sched_enable:
    #  friendly_name: Sobota

    #input_boolean.mower_0_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_1_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_2_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_3_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_4_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_5_cuttoedge:
    #  friendly_name: Cut-to-edge
    #input_boolean.mower_6_cuttoedge:
    #  friendly_name: Cut-to-edge

    # Automations ########
    automation.mower_notify_status:
      friendly_name: Notyfikacja statusu
      icon: mdi:bell
    automation.mower_notify_error:
      friendly_name: Notyfikacja błędu
      icon: mdi:bell

    automation.mower_sync_values:
      friendly_name: Synchronizacja danych
      icon: mdi:sync

    #automation.mower_views_switch:
    #  friendly_name: Toggle tabs
    #  icon: mdi:tab

    # Scripts #########
    script.mower_set_config:
      friendly_name: Zastosuj ustawienia
      icon: mdi:content-save-settings

    script.mower_setzone:
      friendly_name: Wybór strefy
      icon: mdi:vector-difference

    script.mower_setzones:
      friendly_name: Zastosuj wielostrefowość
      icon: mdi:content-save-settings

    script.mower_views_toggle:
      friendly_name: Przełącz zakładki
      icon: mdi:tab
