# Customize #########################################################
homeassistant:
  customize:
  # Switches ###########
    switch.mower_mowing:
      friendly_name: Maaien
    switch.mower_home:
      friendly_name: Huis
    switch.mower_edgecut:
      friendly_name: Randroutine
    switch.mower_partymode:
      friendly_name: Feestmodus
    switch.mower_lock:
      friendly_name: Vergrendeling

  # Sensors ############
    sensor.landroid_mower_battery:
      friendly_name: Batterijpercentage
      device_class: battery
    sensor.landroid_mower_error:
      friendly_name: Fout
    sensor.landroid_mower_status:
      friendly_name: Status

    sensor.mower_ip:
      friendly_name: IP-adres

    sensor.mower_bladetime:
      friendly_name: Werktijd messen
    sensor.mower_current_bladetime:
      friendly_name: Huidige werktijd messen
    sensor.mower_totaltime:
      friendly_name: Totale werktijd
    sensor.mower_distance:
      friendly_name: Totale afstand
    sensor.mower_lastupdate:
      friendly_name: Laatste update
      icon: mdi:update
    sensor.mower_wifi:
      friendly_name: WiFi-kwaliteit
    sensor.mower_yaw:
      friendly_name: Yaw
    sensor.mower_roll:
      friendly_name: Roll
    sensor.mower_pitch:
      friendly_name: Pitch

  # Input Selects ######
    input_select.mower_zone:
      friendly_name: Maaizone

  # Input Numbers ######
    input_number.mower_raindelay:
      friendly_name: Regenvertraging
    input_number.mower_timeextension:
      friendly_name: Tijdsvertraging

    input_number.mower_zone0_distance:
      friendly_name: "Maai zone 0: Afstand"
    input_number.mower_zone1_distance:
      friendly_name: "Maai zone 1: Afstand"
    input_number.mower_zone2_distance:
      friendly_name: "Maai zone 2: Afstand"
    input_number.mower_zone3_distance:
      friendly_name: "Maai zone 3: Afstand"

    input_number.mower_zone0_probability:
      friendly_name: "Maai zone 0: Instelling"
    input_number.mower_zone1_probability:
      friendly_name: "Maai zone 1: Instelling"
    input_number.mower_zone2_probability:
      friendly_name: "Maai zone 2: Instelling"
    input_number.mower_zone3_probability:
      friendly_name: "Maai zone 3: Instelling"

  # Input Booleans #####
    input_boolean.mower_sched_settings:
      friendly_name: Instellingen
    input_boolean.mower_info_toggle:
      friendly_name: Informatie
    input_boolean.mower_zone_enable:
      friendly_name: Multizone inschakelen

    input_boolean.mower_view_config:
      friendly_name: Configuratie
    input_boolean.mower_view_setzones:
      friendly_name: Multizone

    #input_boolean.mower_view_0:
    #  friendly_name: Zo.
    #input_boolean.mower_view_1:
    #  friendly_name: Ma.
    #input_boolean.mower_view_2:
    #  friendly_name: Di.
    #input_boolean.mower_view_3:
    #  friendly_name: Wo.
    #input_boolean.mower_view_4:
    #  friendly_name: Do.
    #input_boolean.mower_view_5:
    #  friendly_name: Vr.
    #input_boolean.mower_view_6:
    #  friendly_name: Za.

    #input_boolean.mower_0_sched_enable:
    #  friendly_name: Zondag
    #input_boolean.mower_1_sched_enable:
    #  friendly_name: Maandag
    #input_boolean.mower_2_sched_enable:
    #  friendly_name: Dinsdag
    #input_boolean.mower_3_sched_enable:
    #  friendly_name: Woensdag
    #input_boolean.mower_4_sched_enable:
    #  friendly_name: Donderdag
    #input_boolean.mower_5_sched_enable:
    #  friendly_name: Vrijdag
    #input_boolean.mower_6_sched_enable:
    #  friendly_name: Zaterdag

    #input_boolean.mower_0_cuttoedge:
    #  friendly_name: Randroutine
    #input_boolean.mower_1_cuttoedge:
    #  friendly_name: Randroutine
    #input_boolean.mower_2_cuttoedge:
    #  friendly_name: Randroutine
    #input_boolean.mower_3_cuttoedge:
    #  friendly_name: Randroutine
    #input_boolean.mower_4_cuttoedge:
    #  friendly_name: Randroutine
    #input_boolean.mower_5_cuttoedge:
    #  friendly_name: Randroutine
    #input_boolean.mower_6_cuttoedge:
    #  friendly_name: Randroutine


  # Automations ########
    automation.mower_notify_status:
      friendly_name: Status notificaties
      icon: mdi:bell
    automation.mower_notify_error:
      friendly_name: Fout notificaties
      icon: mdi:bell

    automation.mower_sync_values:
      friendly_name: Data synchronisatie
      icon: mdi:sync

    #automation.mower_views_switch:
    #  friendly_name: Wissel van tab
    #  icon: mdi:tab


# Scripts #########
    script.mower_set_config:
      friendly_name: Instellingen opslaan
      icon: mdi:content-save-settings

    script.mower_setzone:
      friendly_name: Selectie zone
      icon: mdi:vector-difference

    script.mower_setzones:
      friendly_name: Multizone opslaan
      icon: mdi:content-save-settings

    script.mower_views_toggle:
      friendly_name: Wissel van tab
      icon: mdi:tab
